import { Geist, Geist_Mono } from "next/font/google";
import "../styles/scss/main.scss";
import { getnavbarSection } from "../../firebase/dbController";
import Header from "@/stories/components/organisms/Header/Header";
import Navbar from "@/stories/components/molecules/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const navlinks = await getnavbarSection("navlinks");
  const geforce = await getnavbarSection("GeForceNow");
  const ubisoft = await getnavbarSection("ubisoft");
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-black`}>
        <div className=" position-relative ">
          <Header navlinks={navlinks} geforce={geforce} ubisoft={ubisoft} />

          <main className="position-absolute ms-0 ms-lg-5">
            <Navbar />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
